"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = __importDefault(require("express"));
const authController_1 = __importDefault(require("../Controllers/authController"));
const redFlagsController_1 = __importDefault(require("../Controllers/redFlagsController"));
const interventionsController_1 = __importDefault(require("../Controllers/interventionsController"));
const commentsController_1 = __importDefault(require("../Controllers/commentsController"));
const upvotesController_1 = __importDefault(require("../Controllers/upvotesController"));
const auth_1 = __importDefault(require("../middleware/auth"));
const notificationController_1 = __importDefault(require("../Controllers/notificationController"));
const multer_1 = __importDefault(require("../config/multer"));
const router = express_1.default.Router();
router.post('/auth/signup', authController_1.default.signup);
router.post('/auth/login', authController_1.default.login);
router.get('/auth/profile', auth_1.default.verifyToken, authController_1.default.getProfile);
router.patch('/auth/profile', auth_1.default.verifyToken, authController_1.default.updateProfile);
router.post('/auth/profile/picture', auth_1.default.verifyToken, multer_1.default.single('profile_picture'), authController_1.default.uploadProfilePicture);
router.get('/auth/users', auth_1.default.verifyToken, auth_1.default.isAdmin, authController_1.default.getUsers);
router.get('/red-flags', auth_1.default.verifyToken, redFlagsController_1.default.getAllRedFlags);
router.get('/red-flags/:id', auth_1.default.verifyToken, redFlagsController_1.default.getRedFlag);
router.post('/red-flags', auth_1.default.verifyToken, multer_1.default.any(), redFlagsController_1.default.createRedFlag);
router.patch('/red-flags/:id/location', auth_1.default.verifyToken, auth_1.default.checkRecordOwnership('red_flags'), redFlagsController_1.default.updateLocation);
router.patch('/red-flags/:id/comment', auth_1.default.verifyToken, auth_1.default.checkRecordOwnership('red_flags'), redFlagsController_1.default.updateComment);
router.post('/red-flags/:id/media', auth_1.default.verifyToken, auth_1.default.checkRecordOwnership('red_flags'), multer_1.default.array('media', 2), redFlagsController_1.default.addMedia);
router.delete('/red-flags/:id', auth_1.default.verifyToken, auth_1.default.checkRecordOwnership('red_flags'), redFlagsController_1.default.deleteRedFlag);
router.patch('/red-flags/:id/status', auth_1.default.verifyToken, auth_1.default.isAdmin, redFlagsController_1.default.updateStatus);
router.put('/red-flags/:id', auth_1.default.verifyToken, auth_1.default.checkRecordOwnership('red_flags'), multer_1.default.array('media', 2), redFlagsController_1.default.updateRedFlag);
router.get('/notifications', auth_1.default.verifyToken, notificationController_1.default.getUserNotifications);
router.put('/notifications/read', auth_1.default.verifyToken, notificationController_1.default.markAllAsRead);
router.get('/interventions', auth_1.default.verifyToken, interventionsController_1.default.getAllInterventions);
router.get('/interventions/:id', auth_1.default.verifyToken, interventionsController_1.default.getIntervention);
router.post('/interventions', auth_1.default.verifyToken, multer_1.default.any(), interventionsController_1.default.createIntervention);
router.patch('/interventions/:id/location', auth_1.default.verifyToken, auth_1.default.checkRecordOwnership('interventions'), interventionsController_1.default.updateLocation);
router.patch('/interventions/:id/comment', auth_1.default.verifyToken, auth_1.default.checkRecordOwnership('interventions'), interventionsController_1.default.updateComment);
router.post('/interventions/:id/media', auth_1.default.verifyToken, auth_1.default.checkRecordOwnership('interventions'), multer_1.default.any(), interventionsController_1.default.addMedia);
router.delete('/interventions/:id', auth_1.default.verifyToken, auth_1.default.checkRecordOwnership('interventions'), interventionsController_1.default.deleteIntervention);
router.patch('/interventions/:id/status', auth_1.default.verifyToken, auth_1.default.isAdmin, interventionsController_1.default.updateStatus);
router.put('/interventions/:id', auth_1.default.verifyToken, auth_1.default.checkRecordOwnership('interventions'), multer_1.default.any(), interventionsController_1.default.updateIntervention);
router.get('/:reportType/:reportId/comments', auth_1.default.verifyToken, commentsController_1.default.getComments);
router.post('/:reportType/:reportId/comments', auth_1.default.verifyToken, commentsController_1.default.addComment);
router.delete('/comments/:commentId', auth_1.default.verifyToken, commentsController_1.default.deleteComment);
router.get('/:reportType/:reportId/upvotes', auth_1.default.verifyToken, upvotesController_1.default.getUpvotes);
router.post('/:reportType/:reportId/upvotes', auth_1.default.verifyToken, upvotesController_1.default.toggleUpvote);
exports.default = router;
//# sourceMappingURL=routes.js.map